FROM centos:7
ADD ai-backend /ai-backend
EXPOSE 7099
## operate
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' > /etc/timezone
RUN adduser appuser
RUN cd /
RUN chmod 777 /ai-backend
RUN mkdir /log
RUN chmod -R 777 /log
USER appuser
CMD ["./ai-backend", "pro"]